CREATE DATABASE IF NOT EXISTS lms;
USE lms;

CREATE TABLE PERSON (
    ID INT NOT NULL PRIMARY KEY,
    PNAME VARCHAR(30) NOT NULL,
    PASSWORD VARCHAR(10) NOT NULL,
    ADDRESS VARCHAR(30) NOT NULL,
    PHONE_NO INT NOT NULL
);

CREATE TABLE BOOK (
    ID INT NOT NULL PRIMARY KEY,
    TITLE VARCHAR(30) NOT NULL,
    AUTHOR VARCHAR(20) NOT NULL,
    SUBJECT VARCHAR(20) NOT NULL,
    IS_ISSUED BOOLEAN NOT NULL
);

CREATE TABLE STAFF (
    S_ID INT NOT NULL PRIMARY KEY,
    TYPE VARCHAR(10) NOT NULL,
    SALARY DOUBLE,
    CONSTRAINT FK_STAFF_PERSON FOREIGN KEY (S_ID) REFERENCES PERSON(ID)
);

CREATE TABLE CLERK (
    C_ID INT NOT NULL PRIMARY KEY,
    DESK_NO INT NOT NULL,
    CONSTRAINT FK_CLERK_STAFF FOREIGN KEY (C_ID) REFERENCES STAFF(S_ID)
);

CREATE TABLE LIBRARIAN (
    L_ID INT NOT NULL PRIMARY KEY,
    OFFICE_NO INT NOT NULL,
    CONSTRAINT FK_LIBRARIAN_STAFF FOREIGN KEY (L_ID) REFERENCES STAFF(S_ID)
);

CREATE TABLE BORROWER (
    B_ID INT NOT NULL PRIMARY KEY,
    CONSTRAINT FK_BORROWER_PERSON FOREIGN KEY (B_ID) REFERENCES PERSON(ID)
);

CREATE TABLE BORROWED_BOOK (
    BOOK INT NOT NULL PRIMARY KEY,
    BORROWER INT NOT NULL,
    CONSTRAINT FK_BORROWED_BOOK_BOOK FOREIGN KEY (BOOK) REFERENCES BOOK(ID),
    CONSTRAINT FK_BORROWED_BOOK_BORROWER FOREIGN KEY (BORROWER) REFERENCES BORROWER(B_ID)
);

CREATE TABLE LOAN (
    L_ID INT NOT NULL PRIMARY KEY,
    BORROWER INT NOT NULL,
    BOOK INT NOT NULL,
    ISSUER INT NOT NULL,
    ISS_DATE TIMESTAMP NOT NULL,
    RECEIVER INT,
    RET_DATE TIMESTAMP NULL,
    FINE_PAID BOOLEAN,
    CONSTRAINT FK_LOAN_BORROWER FOREIGN KEY (BORROWER) REFERENCES BORROWER(B_ID),
    CONSTRAINT FK_LOAN_BOOK FOREIGN KEY (BOOK) REFERENCES BOOK(ID),
    CONSTRAINT FK_LOAN_ISSUER FOREIGN KEY (ISSUER) REFERENCES STAFF(S_ID),
    CONSTRAINT FK_LOAN_RECEIVER FOREIGN KEY (RECEIVER) REFERENCES STAFF(S_ID)
);

CREATE TABLE ON_HOLD_BOOK (
    REQ_ID INT NOT NULL PRIMARY KEY,
    BOOK INT NOT NULL,
    BORROWER INT NOT NULL,
    REQ_DATE DATE NOT NULL,
    CONSTRAINT FK_HOLD_BOOK FOREIGN KEY (BOOK) REFERENCES BOOK(ID),
    CONSTRAINT FK_HOLD_BORROWER FOREIGN KEY (BORROWER) REFERENCES BORROWER(B_ID)
);